name: Rust

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}

    strategy:
      matrix:
        include:
          - name: MacOS-14-arm64
            os: MacOS-14
          - name: MacOS-13
            os: macos-13
          # - name: Linux-x64
            # os: ubuntu-latest

    steps:
    - name: Checkout Nonlinear_Adaa
      uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build plugin
      run: cargo xtask bundle Nonlinear_ADAA --release
    - name: zip vst result
      run: zip -r bundled.zip target/bundled
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bundled.zip
        prerelease: true
        body: ""
        tag: ${{ github.ref }}
